### ISSUE TITLE
As a house officer who has to manage a lot of information, I can flag and view the critical issues to follow up for each patient so that I can complete the follow-up as soon as possible.

### ISSUE THREAD

**Issue by gowgos5** [AY1920S1-CS2113-T14-1/main#34]
```Role```: House officer
```Function```: Flag and view the critical issues to follow up for each patient
```Benefit```: Can complete the follow-up as soon as possible

**Comment by aquohn** [comment]
A flagship feature of our product, simple information retrieval on a patient's homepage. If we want to implement the ability to navigate directly from the homepage to a detailed view of the Plan or Observation though, we will need to implement some additional logic so that the user can unambiguously select an item based on what he sees from the GUI.
